### ISSUE TITLE
#1256 closed, but does not work.

### ISSUE THREAD

**Issue by BernardG** [vlachoudis/bCNC#1257] opened 2019-07-26 16:39 UTC
Maybe I did not understand where to enter the code, but it just does not work on a user button, terminal or not. Mostly, I have no idea where to enter the asked value.

**Comment by Harvie** [comment] 2019-07-26 16:41
duplicate of #1256 
you could have just continued to comment there.

**Closed by Harvie** 2019-07-26 16:41 UTC
Labels: duplicate
