### ISSUE TITLE
WIth "Dark" theme,MAIN MENU BAR is Light GRAY with the TEXT in WHITE!!

### ISSUE THREAD

**Issue by lumanga** [vlachoudis/bCNC#1238] opened 2019-06-06 14:17 UTC
Using a "Dark" theme, the MAIN MENU BAR is "Light GRAY" coloured  with the TEXT in WHITE.
In this case is impossible to read the text!

I have found a similar issue here:
https://github.com/vlachoudis/bCNC/issues/450

but witout a solution.. Can be now solved with version bCNC 0.9.14

**Comment by ptvoinfo** [comment] 2019-09-23 11:50
I've migrated to Ubuntu 18.04 and got the exactly the same problem :(.

**Comment by Harvie** [comment] 2019-09-24 10:49
Duplicate of #511

**Closed by Harvie** 2019-09-24 10:49 UTC
Labels: duplicate, user interface
