### ISSUE TITLE
Backlash

### ISSUE THREAD

**Issue by homecncuk** [vlachoudis/bCNC#1276] opened 2019-09-07 10:52 UTC
Hi all newbie here has anyone managed to sort the backlash compensation issue. I have searched but can not find any resolution.

**Comment by MARIOBASZ** [comment] 2019-09-07 13:08
If you search in grbl Github there is someone who worked on it. I have not tried it.

**Comment by Harvie** [comment] 2019-09-07 20:04
Duplicate of #563

**Closed by Harvie** 2019-09-07 20:04 UTC
Labels: duplicate

**Comment by Harvie** [comment] 2021-01-07 22:19
To get backlash compensation please consider using grblHAL instead of GRBL. It will probably not run on atmega, but upgrade is cheap (less than $10). grblHAL can be compiled with backlash compensation support (as well as other improvements to original GRBL). It is now officialy supported by bCNC.

https://github.com/terjeio/grblHAL/
