### ISSUE TITLE
bCNC TinyG and Pi3

### ISSUE THREAD

**Issue by Seb66** [vlachoudis/bCNC#844] opened 2018-05-31 21:15 UTC
Hi,

I have changed out my CNC controller to a TinyG and cannot get the USB port/Connection active.
There is no USB driver other than usb0 and AMAO. When i open usb 0 the prompt says it connected but doesnt change the orange button?

How do i get tinyG to work with bCNC on a Pi3?

**Comment by vlachoudis** [comment] 2018-06-04 13:43
I have a version which **works** (a big word) with TinyG. It lacks still many features in order to be compatible.

**Comment by MARIOBASZ** [comment] 2018-06-04 23:57
Excellent! I want to test the operation of the machine with jerk control and so far only G2Core / Tinyg has implemented it. It would be nice to be able to handle it from BCNC

**Comment by colinluthier** [comment] 2018-06-17 03:54
@vlachoudis Is the TinyG version available as a Beta?

**Comment by Harvie** [comment] 2018-12-01 09:37
Duplicate of #83

**Closed by Harvie** 2018-12-01 09:37 UTC
Labels: duplicate, non-GRBL
