### ISSUE TITLE
Bcnc .exe

### ISSUE THREAD

**Issue by FatNarval** [vlachoudis/bCNC#1024] opened 2018-10-30 20:26 UTC
Hi, I am following recent development of bcnc, and I am very thrilled with new features and passion you guys put in this project!
 Being inspired with this little mighty grbl , I have developed  series of hobby grade cnc machines. Everything started when I wanted to make cnc for my nephew's 18th birthday.
![img-20181030-wa0001](https://user-images.githubusercontent.com/42237246/47748191-7cab5180-dc8a-11e8-91e4-b3ceeb4c759a.jpg)

Being sweeptaway with performance of simple but efficient combination of grbl and T slot construction, I was contemplating to make cnc fabric plotter cutter digitizer using simmilar approach.

The problem was software, bcnc looked promising, and recent development of digitizer encouraged me to build this big ploter cutter digitizer.
![img-20181030-wa0002](https://user-images.githubusercontent.com/42237246/47748182-77e69d80-dc8a-11e8-976e-abc3615544b6.jpg)

![20181021_154236](https://user-images.githubusercontent.com/42237246/47747631-11ad4b00-dc89-11e8-9cb2-84146a53f607.jpg)
![20181021_194840](https://user-images.githubusercontent.com/42237246/47747652-1eca3a00-dc89-11e8-8ea4-4337d88255e1.jpg)

The problem is I still do not use bcnc, I use separate cam app, and use  to export  work coordinates g54 to g59so I save 6 points at the time, and manipulate text to create g code or hpgl files which I can later import as vectors or modify .
I would like to test new features of bcnc but I am no programer, so some simple instalation with .exe file like in issue #437 would be rather helpful.

Best regards!

**Comment by Harvie** [comment] 2018-10-30 21:16
First thing i have to say is that i am going to close this issue, because as you say. It's duplicate of #437 
Any further discussion regarding .exe certainly should take place in that issue. Anyway i haven't used Windows myself for years, so i don't know much about this. It sounds doable, but i hope that some windows user will be able to do this for us. However it shouldn't be too hard to install bCNC on windows. If you got some older version working, you probably only need to install numpy to get latest version working as well.

Secondly your photos are inspiring. Second machine looks very big. Are you going to create clothes on that machine? What kind of tool you use for cutting? I recently added dragknife support and it seems pretty stable to me.

If you are into this stuff, you might also like to google terms "diy cnc embroidery machine". It's just CNC controlled frame, which moves in sewing machine:

![image](https://user-images.githubusercontent.com/276504/47750975-e169aa80-dc90-11e8-8745-aa5c5d307542.png)

**Closed by Harvie** 2018-10-30 21:16 UTC
Labels: cool photos, duplicate, release engineering

**Comment by Harvie** [comment] 2018-10-30 22:59
> 3d, Vcarving, torchoidal milling, ability to run gcode from any chosen line

These are the things that we don't have right now. Except for some very experimental alpha trochoidal support. All of them can be done with relative ease, but it will take some time. V-carving is cool, but i was thinking that there will be no one to implement it. But while i was working on trochoidal strategy and profile overcut code i realized that it can be solved using the same code. Since trochoids have variable diameter in the corners, which is same to the way how v-bit changes it's diameter by retracting in these corners. So it's possible that we'll get trochoid cornering and v-carving in single effort if we do this right.

**Comment by FatNarval** [comment] 2018-10-30 23:12
Wow, that would be great, yes v carve seems to me that can be tricky, since all 3 axes work simultaneosly to produce desired effect.
I do not know how else to help, but I will be more than hapyy to do testing. :)

**Comment by Harvie** [comment] 2018-11-20 16:37
There is now much easier way of installing bCNC on Windows:
https://github.com/vlachoudis/bCNC/issues/964#issuecomment-440315914
