### ISSUE TITLE
AutoLevel Fast Probe Feed Issue

### ISSUE THREAD

**Issue by Skipper-is** [vlachoudis/bCNC#1224] opened 2019-05-04 18:58 UTC
I am using autolevel, and have set the regular probe feed to 10, and the fast feed to 100, but the 100 for fast feed doesn't appear to be applied when moving between sample sites.
If I look at the Gcode:
```
G38.3Z-10F10
[PRB:51.803,0.055,-2.048:1]
ok
G0Z1
ok
G0X51.8028Y11.1778
ok
```
Surely on G0X51Y11 there should be F100?

**Comment by MARIOBASZ** [comment] 2019-05-04 20:33
G0 is fast or transfer speed (which you have set as maximum speed), does not carry F. G1 is milling speed, determined by F.
Read  Gcode no the web

**Comment by Skipper-is** [comment] 2019-05-04 20:36
And G0 should stay on the default feed rate or whatever it was initially set up on (the fast feed rate ideally), and not follow the probing rate, but yet it follows the feed rate of 10 from G38.3

**Comment by Harvie** [comment] 2019-05-04 20:55
Do you use GRBL?

**Comment by Skipper-is** [comment] 2019-05-04 22:20
The Smoothieboard

**Comment by Harvie** [comment] 2019-05-04 22:24
Duplicate of #1169

**Closed by Harvie** 2019-05-04 22:24 UTC
Labels: autoleveling and probing, duplicate, non-GRBL
