### ISSUE TITLE
Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

### ISSUE THREAD

**Issue by RyuuzakiJulio** [vlachoudis/bCNC#1141] opened 2019-01-18 17:08 UTC
Trying to install on a Mac. I do have this library already installed "numpy" but it wants to uninstall it? I don't get it. here is the log:

```
python -m pip install --upgrade bCNC                                                                                     [2:02:47]
Collecting bCNC
  Downloading https://files.pythonhosted.org/packages/51/64/f58378627ae712ddc0086293b4b832fe221de64fa105de4c476a4b0b0805/bCNC-0.9.14.52.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 11.6MB/s 
Requirement already satisfied, skipping upgrade: pyserial<=3.0.1 in /Library/Python/2.7/site-packages (from bCNC) (3.0.1)
Collecting numpy>=1.12 (from bCNC)
  Downloading https://files.pythonhosted.org/packages/e4/97/167eb80dadcf2905b58d66ada6c128d3ec5e8595beb02457b881e7399be3/numpy-1.16.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (13.9MB)
    100% |████████████████████████████████| 13.9MB 2.4MB/s 
Collecting Pillow>=4.0 (from bCNC)
  Downloading https://files.pythonhosted.org/packages/7e/bb/d502ae951099ce9a5a20dec21e577f304b7706321f83205c5215ebc028cd/Pillow-5.4.1-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (3.7MB)
    100% |████████████████████████████████| 3.7MB 6.3MB/s 
Installing collected packages: numpy, Pillow, bCNC
  Found existing installation: numpy 1.8.0rc1
Cannot uninstall 'numpy'. It is a distutils installed project and thus we cannot accurately determine which files belong to it which would lead to only a partial uninstall.

```

**Comment by Harvie** [comment] 2019-01-18 17:47
what if you try this? `pip install --ignore-installed bCNC`

**Comment by RyuuzakiJulio** [comment] 2019-01-18 19:06
Thank you for your reply. It ended up working with something close to that.

sudo pip2 install --upgrade --ignore-installed --install-option '--install-data=/usr/local' numpy

and then just running the installation again.

**Comment by rohitsg** [comment] 2019-11-01 09:55
worked for me - `sudo pip install --upgrade --ignore-installed --install-option '--install-data=/usr/local' numpy`

**Comment by Harvie** [comment] 2019-11-01 12:23
If i understood it correctly. This is basicaly caused by the fact, that you or your system have previously installed numpy by some other means than using pip. So i guess i will close the issue. If there is something i can do about this on side of bCNC, please don't hesitate to write the comment and i will reopen this, so we can fix it.

**Closed by Harvie** 2019-11-01 12:23 UTC
Labels: OS Mac, release engineering

**Comment by Harvie** [comment] 2026-04-21 21:03
Hello guys, some offtopic mesage: There is new bCNC version coming and it's really challenging to get it working on Mac OS, because i don't have mac.
Currently the new version resides in https://github.com/koneklaudio/bCNC but i will merge it soon. Can you please help me debug it on MacOS? We are discussing the issues here: https://github.com/vlachoudis/bCNC/issues/591
