### ISSUE TITLE
camera not working bcnc raspberry pi

### ISSUE THREAD

**Issue by mikeymp** [vlachoudis/bCNC#1236] opened 2019-06-02 22:08 UTC
My bcnc install works well on my raspberry pi 3b i just need to know where in bcnc do you set up a usb camera? All packages needed are up to date and newest as of today. Cannot get crosshairs or video screen for bcnc to show but icon is no longer grayed out just the camera setting tool .Where in bcnc do you make the changes to get camera to work?

**Comment by mikeymp** [comment] 2019-06-08 02:24
i now have a good install of basic opencv detects my camera i ran calibration .py video.py and videov412.py from opencv folder camera works on all but not detected by bcnc cv2 also returns true no errors.

**Comment by mikeymp** [comment] 2019-06-09 21:12
it all works good now camera is up and working and works well even over ssh .I was the problem all software works with no errors. Thank  you for providing a great product that has awesome features and somewhat easy to use for a new guys first Cnc build.

**Comment by Harvie** [comment] 2019-06-10 07:45
duplicate of #1235

**Closed by Harvie** 2019-06-10 07:45 UTC
