### ISSUE TITLE
Improve GUI (flat ? ) 

### ISSUE THREAD

**Issue by masterleo** [vlachoudis/bCNC#686] opened 2017-10-27 09:58 UTC
I think the icons should be flat design and with 3 colors only. like this : 
![97ff4303099f0800a59a47a6bbb45e4a--flat-design-app-design](https://user-images.githubusercontent.com/8157302/32098775-0f2d4d50-bb0e-11e7-874c-58ef9bec607b.jpg)

**Comment by masterleo** [comment] 2017-10-27 09:59
If you are ok with that or agree please reply to me and say it.

**Comment by vlachoudis** [comment] 2017-10-27 11:57
Closed as duplicate of #679

**Closed by vlachoudis** 2017-10-27 11:57 UTC
