### ISSUE TITLE
Open gcode very large file, wait a long time to prepare

### ISSUE THREAD

**Issue by viewsat** [vlachoudis/bCNC#272] opened 2016-03-22 02:24 UTC
I opened this gcode test of 97 million lines to be tested,wait a long time to prepare.
http://www.picengrave.com/downloads/darklylabs/Roy%20Rogers%20Metric.zip

When I use the latest Universal Gcode Sender open this gcode test, wait 10 seconds to read gcode,

**Comment by atrueresistance** [comment] 2016-03-22 04:04
@viewsat I use bCNC for laser code all the time. Turn off the render
![capture](https://cloud.githubusercontent.com/assets/7239809/13941771/18b13fac-efb9-11e5-984e-7f6a8c18086f.PNG) and it will load in 20 seconds.

**Comment by vlachoudis** [comment] 2016-03-22 07:00
Python is not very fast as language, so rendering can be long. Also it is in my plans to optimize via threads the sender.

**Comment by tuxun** [comment] 2016-04-11 13:23
Hi.
@vlachoudis maybe bCNC should warn us between gcode file loading and render starting? The fact is I would like to see: "loading (in ram) done (in XXX millisecond), rendering the ram gcode (work in progress X% )" ;)

**Comment by Effer** [comment] 2016-04-11 14:38
I've to say that this is the most annoying limitation of bCNC. Hit start and then wait till everything is loaded, even if GRBL can buffer only very few lines of gcode.
I'm confident in @vlachoudis to take care of this, and if you need some Beta tester let me know.

**Comment by vlachoudis** [comment] 2016-04-12 17:14
The long waited feature by @Effer and requested by others as well @wolfmanjm is now there. The new master is queueing the commands immediately the moment you press "Run" and is processing the remaining in the background. So once you click "Run" the response should be immediate. Could you please test it.

**Comment by Effer** [comment] 2016-04-12 17:34
Wonderful, tonight will be a test night!

**Comment by Effer** [comment] 2016-04-12 19:38
First 50K lines done! (Scrap wood)

![wp_20160412_21_11_44_pro](https://cloud.githubusercontent.com/assets/1007007/14472844/6b229cde-00f5-11e6-8028-dbba7a129155.jpg)

Great job @vlachoudis it starts in a flash and run smooth and without issue. It's a pleasure run the code without that annoying wait. Thank you!

The only drawback (I know it now will seem "fussy") is that soon after start is not possible to stop neither pause the job with the software button.

**Comment by vlachoudis** [comment] 2016-04-13 07:47
@Effer I afraid you are right. The same thread that does the preparation of the g-code is also watching the buttons, so as long the gcode is prepared the GUI is inactive. I thing I have one solution I will try it later today.

**Comment by vlachoudis** [comment] 2016-04-14 07:14
In the current master the "Stop" and "Pause" are active during submitting.
Also to make it more responsive I've put a timer of 5s in the drawing in canvas. So in case there is a huge file that takes more than 5s to draw it will interrupt the rendering. It is user configurable in the .bCNC ini file. However I have to put an easier configuration directly from the canvas. I am thinking of a dropdown combox that one can choose directly the rendering time from 1, 2, 5, 10, 20, 30, 60, infinite

**Comment by Effer** [comment] 2016-04-14 19:06
Sorry to report that the issue with bCNC resuming the job after a stop by itself, is still there.
The status bar report "Run ended" but bCNC keep on streaming. Also you can exit the programm without the usual warning.

**Comment by Effer** [comment] 2016-04-14 19:16
It seems to happen more often with big files. When hit stop I get this error:

![untitled2](https://cloud.githubusercontent.com/assets/1007007/14540581/11024316-0286-11e6-848c-4959f2820bdd.png)

Then after 5-6 seconds bCNC start streaming again by itself.

**Comment by vlachoudis** [comment] 2016-04-20 17:08
In linux where I am testing it works fine and I cannot reproduce this problem. Maybe it is related with windows.

**Comment by Effer** [comment] 2016-04-28 18:38
Any suggestion in how to debug? I can't reproduce everytime but is still there with latest version.

**Comment by vlachoudis** [comment] 2016-04-28 19:59
Can you try the latest version I think I found the probem

**Comment by st0jko** [comment] 2016-04-30 11:36
First let me state that I love this piece of software and would like to thank everyone working on it. 

Now about Effer's problem.. I just experienced the same thing. I hit stop and bCNC seemed to just jump to another piece of code and continue to work there. It actually ruined the piece but whatever.. I had to hit stop multiple times, because it seemed to just jump to another piece of code to work from. Like the code was broken into smaller chunks, because it was so large(130k lines), and hitting stop just stopped current chunk, but not other that follow.

Anyway.. hope this helps.

**Comment by vlachoudis** [comment] 2016-04-30 16:01
@st0jko in which OS you are running?

**Comment by st0jko** [comment] 2016-04-30 16:49
Windows 10 pro x64 and windows 7 ultimate x86

**Comment by Effer** [comment] 2016-05-02 19:56
@vlachoudis I can reproduce in both Win7 and WinXp.
From my test the stopRun method in Sender.py is executed, but not the checkStop method in bCNC.py.

**Comment by vlachoudis** [comment] 2016-05-03 10:58
@Effer @st0jko could you please try the new master. I think I found it this time.

**Comment by Effer** [comment] 2016-05-03 16:53
@vlachoudis first tests are succesfull. More test from @st0jko are wellcome.
Thanks!

**Comment by vlachoudis** [comment] 2016-05-03 16:57
@Effer my guess is that the os.sleep(1) in windows was blocking the background thread on windows.

**Comment by Effer** [comment] 2016-05-03 17:07
I was just asking for explanation in PM.. you read my mind again.
That's fully compatible with some of the strange output I've eneconter in my test.

**Comment by vlachoudis** [comment] 2016-05-04 18:31
I am pretty confident that the last commit fixed the problem. So I am closing the issue, unless if it happens again.

**Closed by vlachoudis** 2016-05-04 18:31 UTC
Labels: enhancement

**Comment by st0jko** [comment] 2016-05-07 13:10
Can confirm. Working well now.

**Comment by vlachoudis** [comment] 2016-05-07 18:49
Thanks @st0jko
