### ISSUE TITLE
text generator

### ISSUE THREAD

**Issue by dodolbysuround** [vlachoudis/bCNC#1461] opened 2020-09-17 20:57 UTC
Hi, I think there is a problem with text generator. 
I get a message saying:
"text abort: That's embarrassing, I can't read thin font file" 
whatever the file I try ti use
Any idea?

**Comment by dodolbysuround** [comment] 2020-09-30 19:35
@Harvie , no idea by chance?

**Comment by dodolbysuround** [comment] 2020-10-02 21:23
here is the message

**Comment by bosd** [comment] 2020-11-16 17:23
Duplicate of #1444 .
Assume this is fixed now.

**Closed** 2021-01-07 21:46 UTC
