### ISSUE TITLE
Islands?

### ISSUE THREAD

**Issue by vederstein** [vlachoudis/bCNC#471] opened 2016-12-26 12:20 UTC
I'm very impressed in your software and congrats to you.

I do have a feature enhancement request though (along with the multitude of others out there):

It would be very advantageous for the addition of the creating of "islands."  Many 2-1/2 and 3D cam systems have this.  The operator chooses an outer and inner boundary.  The pocket is the area between the boundaries.

For my use it would be to mill a index pin onto a flange plate.  The pin would then go into the hole on another plate assuring concentrically of the two components.

Thank you for your time.

**Comment by vlachoudis** [comment] 2016-12-27 12:41
Its something on my TODO list, however recently I don't have enough time to work on that.

**Comment by Harvie** [comment] 2018-07-02 14:36
duplicate of #220

**Closed** 2018-10-29 22:17 UTC
Labels: enhancement
