### ISSUE TITLE
box tool dz bug

### ISSUE THREAD

**Issue by spanner888** [vlachoudis/bCNC#1163] opened 2019-02-13 04:51 UTC
Looks like a copy paste error in the box tool.
		if nx > 0:
			self.nx = int(nx)
		else:
			self.nx = int(round(self.dx/nx))

		if ny > 0:
			self.ny = int(ny)
		else:
			self.ny = int(round(self.dy/ny))

		if ny > 0:
			self.nz = int(nz)
... so the code has TWO if ny > 0: .. and no if nz > 0:

Should the last one on line 74 actually be "if nz > 0:" ??

**Comment by Harvie** [comment] 2019-02-13 09:12
Does this cause any problems?

**Comment by sfinexer** [comment] 2019-02-19 17:56
Yes this is a mistake.
Of course, if nz> 0:

**Comment by Harvie** [comment] 2019-02-21 11:30
But can you explain what unexpected behaviour this causes? I don't want to read the code just to figure out what the real world consequence is, since you already know it.

**Comment by Harvie** [comment] 2019-02-26 21:00
Should be fixed by #1170

**Closed by Harvie** 2019-02-26 21:00 UTC
