### ISSUE TITLE
To open all code on the screen

### ISSUE THREAD

**Issue by sfinexer** [vlachoudis/bCNC#960] opened 2018-09-06 21:03 UTC
To open all code on the screen
It is necessary to remove restriction on quantity of the displayed code (blocks) on the screen, it is necessary for allocation of a part of a code and its editing (removal of the selected fragments).

In this case not all G-code which is in the file in case of his big size is displayed.

**Comment by sfinexer** [comment] 2018-09-07 19:17
Help to remove this restriction.
It prevents editing, in particular, removal of G-Code blocks because because of the fact that the point isn't displayed, can't allocate it.

**Comment by Harvie** [comment] 2018-09-10 01:06
Please increase this timeout value in corner of view:

![image](https://user-images.githubusercontent.com/276504/45271318-72e54900-b4a6-11e8-955f-22b50d5b42e9.png)

This can't get properly fixed until #591 is solved.

**Comment by sfinexer** [comment] 2018-09-10 05:39
@Harvie.
It's a go.
In that case, it is necessary to display probably the message that loading is interrupted on the expiration of time.

**Comment by Harvie** [comment] 2018-09-10 13:54
Yes. Maybe. But i personaly think it would make more sense to invest time to bring real OpenGL support, which would provide faster graphics #591

**Comment by Guenni75** [comment] 2018-09-12 20:32
Real 3D in bcnc .... goose bumps!!

**Comment by Harvie** [comment] 2018-10-30 01:14
Closing duplicate of #591

**Closed by Harvie** 2018-10-30 01:14 UTC
