### ISSUE TITLE
bCNC fitted to 5 inch LCD Screen

### ISSUE THREAD

**Issue by lyatesbme** [vlachoudis/bCNC#1265] opened 2019-08-12 23:32 UTC
I am using a 5" LCD screen for bCNC to control a 3018 CNC unit. It loads up well using the availble image that includes the bCNC but I can't seem to fit it to the screen and there is functions off screen.
I have seen an old thread about this and the term used was to "undecorate" but can't seem to find any later references. Can you help and/or advise.
Many thanks

**Comment by Harvie** [comment] 2019-08-26 16:48
Duplicate of #1033 , please feel free to continue there. Also mention resolution of your LCD rather than it's physical size.

**Closed by Harvie** 2019-08-26 16:48 UTC
Labels: duplicate

**Comment by lyatesbme** [comment] 2019-08-27 02:06
Many thanks for your repsonse

Larry Yates
Manager Biomedical Engineering and Technology.
President S.M.B.E. N.S.W.
B. Adult Ed, Diploma Electr. Eng, Grad Cert Public Sector Management
02 68097936     0429660091
larry.yates@health.nsw.gov.au
